name: gstsync
description: GST Filing and Invoice Management App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+3

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.0.5
  equatable: ^2.0.5
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.3.3
  pdf: ^3.10.4
  path_provider: ^2.1.1
  share_plus: ^12.0.0
  shared_preferences: ^2.2.1
  printing: ^5.11.0
  firebase_core: ^4.1.0 
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  csv: ^6.0.0
  file_picker: ^10.3.3
  permission_handler: ^12.0.1
  device_info_plus: ^11.3.0
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^29.1.38
  excel: ^4.0.2
  
  # HTTP Client for WhatsApp API
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

# Configuration for flutter_native_splash
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  
  # Optional parameters are listed below. To enable a parameter uncomment the line by removing the #.
  
  # color_dark: "#042a49"
  # image_dark: assets/images/splash-invert.png
  
  android_12:
    image: assets/images/logo.png
    # icon_background_color: "#111111"
    
  web: false
